### ISSUE TITLE
Add the option to turn it off

### ISSUE THREAD

**Issue by henningBunk** [webosbrew/custom-screensaver#4]
So i got a problem. I installed it and now the screensaver turns on every few minutes when watching apple+.

I deactivated the toggle restarted the tv and even deinstalled the app. Nothing works the screensaver is still there.

Is there an option to turn it off?

**Comment by Informatic** [comment]
Hmmmm...

Weird. Uninstalling the app and rebooting (an actual full proper reboot - either by unplugging and replugging power, running `reboot` on the shell, or just pressing Reboot in Homebrew Channel Settings) should revert any changes we make, since they are just done in runtime by overlaying system files.

**Comment by henningBunk** [comment]
A gotcha! I only used the standby button on the remote. Fixed now after a proper reboot.

Thanks for the swift help :)

I have no idea how to close issues in the github app, maybe I dont have the rights? Can you do this for me?
